### ISSUE TITLE
Support last.fm scrobbling

### ISSUE THREAD

**Issue by lfranchi** [ilTofa/rposx#10]
It would be awesome if this supported scrobbling to last.fm! There aren't a lot of great ways to listen to RP and scrobble the played tracks.

**Comment by ilTofa** [comment]
It can be made, having time to do it. 😊 
Do you really think there is still people using last.fm? 😉

**Comment by lfranchi** [comment]
I think people still scrobble :)

**Comment by ilTofa** [comment]
Version 2.x (available on the store) scrobbles. 😉
