### ISSUE TITLE
Use native "Next Song" keys on OSX Keyboard

### ISSUE THREAD

**Issue by besi** [ilTofa/rposx#11]
The native OSX Keyboard media keys could be used like so:

- When I press the "Next", "Play something different" is activated.
- The client can be paused
- Pressing the back button could jump back to the currently playing song of RP

![media](https://cloud.githubusercontent.com/assets/160412/8132901/3b5d8d6c-1125-11e5-8224-e2b220a8a576.jpg)

See this [StackOverflow article](http://stackoverflow.com/a/3885555/784318):

> I accomplished this in my own application by subclassing NSApplication (and setting the app's principal class to this subclass). It catches seek and play/pause keys and translates them to specific actions in my app delegate.
> 
> Relevant lines:
> 
>     #import <IOKit/hidsystem/ev_keymap.h>
>     
>     - (void)sendEvent:(NSEvent *)event
>     {
>     	// Catch media key events
>     	if ([event type] == NSSystemDefined && [event subtype] == 8)
>     	{
>     		int keyCode = (([event data1] & 0xFFFF0000) >> 16);
>     		int keyFlags = ([event data1] & 0x0000FFFF);
>     		int keyState = (((keyFlags & 0xFF00) >> 8)) == 0xA;
>     		
>     		// Process the media key event and return
>     		[self mediaKeyEvent:keyCode state:keyState];
>     		return;
>     	}
>     	
>     	// Continue on to super
>     	[super sendEvent:event];
>     }
> 
>     - (void)mediaKeyEvent:(int)key state:(BOOL)state
>     {
>     	switch (key)
>     	{
>     		// Play pressed
>     		case NX_KEYTYPE_PLAY:
>     			if (state == NO)
>     				[(TSAppController *)[self delegate] togglePlayPause:self];
>     			break;
>     
>     		// Rewind
>     		case NX_KEYTYPE_FAST:
>     			if (state == YES)
>     				[(TSAppController *)[self delegate] seekForward:self];
>     			break;
>     			
>     		// Previous
>     		case NX_KEYTYPE_REWIND:
>     			if (state == YES)
>     				[(TSAppController *)[self delegate] seekBack:self];
>     			break;
>     	}
>     }
>     
>

**Comment by ilTofa** [comment]
Unfortunately this code don't work on sandboxes application (as Radio Paradise is, distributed through the App Store). Sorry.

**Comment by ilTofa** [comment]
Sandboxed, not sandboxes (stupid auto-corrector, sorry).

**Comment by ilTofa** [comment]
Cannot fix on MAS application. Sorry.
