### ISSUE TITLE
Clicking the song does not open Safari

### ISSUE THREAD

**Issue by besi** [ilTofa/rposx#12]
I've been using RP for quite a while and today when a song played that I liked I wanted to rate it, opening the song in Safari.app.

But clicking a Song does no longer seem to open my browser.

```
Version of RP: 2.0 (98)
OSX 10.11.6
```

**Comment by ilTofa** [comment]
Just tap the (i) button and you'll find a native interface for rating (and commenting). From there, you can also reach the song page on the web site, tapping the button with the RP logo.
As a side note, the code for version 2.x is not here at the moment. 😊
