### ISSUE TITLE
App no longer in app store

### ISSUE THREAD

**Issue by jaraco** [ilTofa/rposx#16]
Today I went to install this app, but it's no longer available in the app store. I guess it got pulled? Any chance you're planning to restore it?

**Comment by ilTofa** [comment]
I'm not in charge of the Radio Paradise and I was not the one pulling it (sorry). The coordinated image of RP changed in last months, and this app is still on the old graphics (and that's probably the reason it was pulled).
In any case, there is a developer signed build on http://www.iltofa.com/rphd/rp.latest.zip
